apiVersion: v1
kind: Service
metadata:
  annotations:
    appname: gobg
  labels:
    app: gobg
  name: gobg
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: gobg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    appname: gobg
  labels:
    app: gobg
  name: gobg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gobg
  strategy: {}
  template:
    metadata:
      annotations:
        appname: gobg
      labels:
        app: gobg
    spec:
      containers:
      - image: christianh814/gobg:green
        name: gobg
        resources: {}
