apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: gobg
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: christianh814/gobg:blue
